#! /usr/bin/env python3
## imports ##
from multiprocessing import JoinableQueue
from pathlib import Path

from twitter_api import TwitterAPI
from user_list import UserList
from user_media import UserMediaCollector, UserMediaDownloader

from argument_handler import args
from config import set_bearer_token, bearer_token

## setup ##
if args.bearer_token is not None:
    set_bearer_token(args.bearer_token)

twitter_api = TwitterAPI(bearer_token)

download_queue = JoinableQueue()
UserMediaDownloader(download_queue).start()

## 
def create_user_processes(user_list):
    global twitter_api, download_queue
    proc_list = []
    for username in user_list:
       proc_list.append(UserMediaCollector(username, twitter_api, download_queue, args.pictures_only, args.videos_only, args.update)) 
    return proc_list

if __name__ == '__main__':
    
    proc_list = []

    if args.list is not None:
        proc_list += create_user_processes(UserList(args.list))
    
    if args.username:
        proc_list += create_user_processes(args.username)
            
    for proc in proc_list:
        proc.start()
    for proc in proc_list:
        proc.join()

    download_queue.join()
